### ISSUE TITLE
Does not work with OBS on Mac Catalina

### ISSUE THREAD

**Issue by timconsidine** [KopiasCsaba/StreamFixerBrowserExtension#1]
I followed the video tutorial, which is excellent.
But when adding Window Capture in OBS, the screenfixer stream is not displayed as an option

**Comment by KopiasCsaba** [comment]
I would advise you to try that again, I think you might have missed something!

If you have a browser window with the streams, then you could stream that in obs. If not then you might not have the screengrab enabled in your obs, or something else happened. But maybe you skipped some steps along the way!

Let me know how did it went, if there is a problem please provide more details!

Closing until that.
