### ISSUE TITLE
Self-hosted JITSI

### ISSUE THREAD

**Issue by timconsidine** [KopiasCsaba/StreamFixerBrowserExtension#3]
I cannot set the chrome extension permission to read/write data for a site which is self-hosted JITSI

**Comment by KopiasCsaba** [comment]
For that you'll need to compile the extension for yourself!

If you are self hosting jitsi, i don't think it will be hard for you!

 * https://github.com/KopiasCsaba/StreamFixerBrowserExtension/blob/master/docs/development.md
 * Check out the code
 * Edit the manifest.json file in folders "firefox" and "chrome" to include your designated url.
 * Execute the three scripts listed in the docs to setup/compile/package the extension and install it in the way it is described there!

Let me know if you have any issues!

**Comment by KopiasCsaba** [comment]
O, i forgot to mention, that you will need to edit ext.tsx where you can change jitsi's url too.
